/**
 * Firmware Code Generate Action
 * 
 * Generates C source code from MorPex YAML knowledge base.
 * Uses xjmcu_workflow.py or directly queries MorPex Memory KB.
 */

import { execSync } from 'child_process';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { writeFileSync, existsSync, mkdirSync } from 'fs';

const __dirname = dirname(fileURLToPath(import.meta.url));

export interface GenerateInput {
  chip: string;
  requirement: string;
  outputDir?: string;
  useWorkflow?: boolean;
}

export interface GenerateOutput {
  success: boolean;
  sourcePath?: string;
  code?: string;
  errors?: string[];
}

const TOOLCHAIN = resolve(__dirname, '../../../../../AstroM/_archive/toolchains/AstroMcu');
const MEMORY_DB = resolve(__dirname, '../../../../../Morpex/data/memory.db');

export async function generateAction(context: any, input: GenerateInput): Promise<GenerateOutput> {
  const { chip, requirement, outputDir, useWorkflow } = input;

  if (!chip) throw new Error('chip is required');
  if (!requirement) throw new Error('requirement is required');

  const outDir = outputDir || resolve(process.cwd(), 'build/generated');
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

  // Option 1: Use the full xjmcu_workflow.py (if available)
  if (useWorkflow !== false) {
    try {
      const result = execSync(
        `python xjmcu_workflow.py --chip ${chip} --req "${requirement}"`,
        { cwd: TOOLCHAIN, encoding: 'utf-8', timeout: 60_000 }
      );
      return { success: true, code: result };
    } catch (err: any) {
      // Fall through to direct generation
    }
  }

  // Option 2: Direct template-based generation
  const sourcePath = resolve(outDir, `${chip}_generated.c`);
  
  // Query memory DB for chip info
  let code = `// ${chip} - Generated by MorPex Firmware Workflow\n`;
  code += `// Requirement: ${requirement}\n\n`;
  code += `#include "${chip}.h"\n\n`;
  code += `void main(void) {\n`;
  code += `    while(1) {\n`;
  code += `        // User code here\n`;
  code += `    }\n`;
  code += `}\n`;

  writeFileSync(sourcePath, code, 'utf-8');

  return {
    success: true,
    sourcePath,
    code,
  };
}
