/**
 * EventTypes — 全系统事件类型常量（SYSTEM_EVENT_TYPES：goal/execution/evaluation/evolution 事件名映射，供 emit/消费方统一引用）
 */
export const SYSTEM_EVENT_TYPES = {
  GOAL_CREATED: 'goal.created',
  GOAL_UNDERSTOOD: 'goal.understood',
  GOAL_REJECTED: 'goal.rejected',
  MISSION_CREATED: 'mission.created',
  MISSION_PHASE_CHANGED: 'mission.phase_changed',
  MISSION_STATUS_CHANGED: 'mission.status_changed',
  MISSION_BLOCKED: 'mission.blocked',
  MISSION_BLOCK_RESOLVED: 'mission.block_resolved',
  MISSION_RISK_ADDED: 'mission.risk_added',
  MISSION_COMPLETED: 'mission.completed',
  // ── U2+U3：DAG 步骤级事件（事件溯源编排，PersistentMissionStore 重放用）──
  STEP_STARTED: 'step.started',
  STEP_COMPLETED: 'step.completed',
  STEP_FAILED: 'step.failed',
  STEP_SKIPPED: 'step.skipped',
  STEP_RETRY: 'step.retry',
  PLAN_CREATED: 'plan.created',
  PLAN_APPROVED: 'plan.approved',
  PLAN_FAILED: 'plan.failed',
  EXECUTION_STARTED: 'execution.started',
  EXECUTION_COMPLETED: 'execution.completed',
  EXECUTION_FAILED: 'execution.failed',
  TASK_COMPLETED: 'task.completed',
  TASK_FAILED: 'task.failed',
  AGENT_ASSIGNED: 'agent.assigned',
  AGENT_CALL_STARTED: 'agent.call_started',
  AGENT_CALL_COMPLETED: 'agent.call_completed',
  AGENT_CALL_FAILED: 'agent.call_failed',
  TOOL_CALLED: 'tool.called',
  TOOL_SUCCEEDED: 'tool.succeeded',
  TOOL_FAILED: 'tool.failed',
  ARTIFACT_CREATED: 'artifact.created',
  ARTIFACT_TRANSITIONED: 'artifact.transitioned',
  ARTIFACT_APPROVED: 'artifact.approved',
  EVALUATION_SCORED: 'evaluation.scored',
  EVALUATION_DECIDED: 'evaluation.decided',
  /** L6 低分事件：missionQuality 低于阈值时发射，L7 演化只消费事件、禁止被 L4 直接触发 */
  EVALUATION_LOW_SCORE: 'evaluation.low_score',
  /** L6 审计事件：产物验证完成（Wave 9.7） */
  EVALUATION_VERIFICATION_COMPLETED: 'evaluation.verification.completed',
  /** L4 审计事件：经验提取（Wave 9.7） */
  BRAIN_LEARNING_EXPERIENCE_EXTRACTED: 'brain.learning.experience_extracted',
  EXPERIENCE_MINED: 'experience.mined',
  PATTERN_EXTRACTED: 'pattern.extracted',
  CAPABILITY_UPDATED: 'capability.updated',
} as const;
